on:
  workflow_call:
    inputs:
      repository:
        required: true
        type: string
      imageName:
        required: true
        type: string
      azureClientId:
        required: true
        type: string
      azureSubscriptionId:
        required: true
        type: string
      azureTenantId:
        required: true
        type: string
      folder:
        required: false
        type: string
        default: ./
          
jobs:
  build:
    runs-on: [linux, self-hosted]
    steps:
    - uses: actions/checkout@v3
    
    - uses: Azure/login@v1
      with:
        auth-type: IDENTITY
        client-id: ${{ inputs.azureClientId }}          
        tenant-id: ${{ inputs.azureTenantId }}
        subscription-id: ${{ inputs.azureSubscriptionId }}
        enable-AzPSSession: true