name: Deploy DevContainer Features

on:
  push:
    branches: 
      - "main"
      - "issues/sjt/refactor-devcontainers"
    paths:
      - ".devcontainer/features/**"    
      - ".github/workflows/devcontainer-features.yaml"
      
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3      

    - name: "Publish Features"
      uses: devcontainers/action@v1
      with:
        publish-features: "true"
        base-path-to-features: "./.devcontainer/features"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}