on:
  workflow_call:
    inputs:
      imageName:
        required: true
        type: string
      tag:
        required: true
        type: string
      platforms: 
        type: string
        default: '[ "linux/amd64", "linux/arm64" ]'
    secrets:
      DOCKERHUB_USERNAME:
        required: true
      DOCKERHUB_TOKEN:
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        platform: ${{ fromJSON(inputs.platforms) }}

    steps:
    - uses: actions/checkout@v3      
    
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - uses: docker/build-push-action@v5.1.0

    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        push: true
        tags: lscsde/${{ inputs.imageName }}:${{ inputs.tag }}
        platforms: ${{ matrix.platform }}