on:
  workflow_call:
    inputs:
      symver:
        description: The symver value for this check-in
        type: string
      
jobs:
  createbranch:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      
    - name: Create Release Branch
      run: |
        git config --global user.name 'lsc-sde'
        git config --global user.email 'shaun.turner1@nhs.net'
        git branch release/${{ inputs.symver }}
        git push