name: CRD Java Model Generate
on:
  workflow_call:
    inputs:
      repository:
        type: string
        required: true
        description: 'The repository where the files are to be exported'
      crds:
        type: string
        required: true
        description: 'Comma-separated paths to CRD yaml sources, can be either HTTP url or local file path.'
      generatingJavaPackage:
        type: string
        required: true
        description: 'The package name of the generated java project.'
      crdApiGroupPrefix:
        type: string
        required: false
        description: 'The prefix of the target CRDs api group to generate. (Optional)'

env:
  IMAGE_NAME: ghcr.io/kubernetes-client/java/crd-model-gen
  IMAGE_TAG: v1.0.6
  GEN_DIR: crd-gen

permissions:
  contents: read

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run CRD Model Generation
        run: |
          export pwd=$(pwd)
          read CRD_SRC_ARGS < <(echo '${{ inputs.crds }}' | perl -ne 'print join " ", map {"-u $ENV{pwd}/$_"} split /,/')
          test -z ${{ inputs.crdApiGroupPrefix }} || export CRD_API_GROUP_ARGS="-n ${{ inputs.crdApiGroupPrefix }}"
          echo "CRD Src Args: ${CRD_SRC_ARGS}"
          echo "CRD Api Group Prefix Args: ${CRD_API_GROUP_ARGS}"
          echo "PWD: ${pwd}"
          echo "GEN_DIR: ${GEN_DIR}"
          mkdir -p ${GEN_DIR}
          docker run \
            --rm \
            -v /var/run/docker.sock:/var/run/docker.sock \
            -v "${pwd}":"${pwd}" \
            --network host \
            ${IMAGE_NAME}:${IMAGE_TAG} \
            /generate.sh \
            ${CRD_SRC_ARGS} \
            ${CRD_API_GROUP_ARGS} \
            -p ${{ inputs.generatingJavaPackage }} \
            -o "${pwd}/${GEN_DIR}"
          ls -lh ${GEN_DIR}
      - uses: actions/upload-artifact@v4
        with:
          name: generated-java-crd-model
          path: |
            ${{ env.GEN_DIR }}
            
  update-repository:
    runs-on: ubuntu-latest
    needs: generate
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        repository: ${{ inputs.repository }}
        token: ${{ secrets.REPOS_RW_TOKEN }}


    - name: Prepare Repository
      run: |
        git config --global user.name 'lsc-sde'
        git config --global user.email 'shaun.turner1@nhs.net'
        git switch "main"
        git fetch

    - uses: actions/download-artifact@v4
      with:
        name: generated-java-crd-model
        
    - name: Update Markdown and check-in changes
      run: |
        echo "This repository was last updated by ${GITHUB_ACTION}/${GITHUB_JOB} on ${GITHUB_REPOSITORY}" > Auto-Generated.md
        git add *
        git commit -m "updated by ${GITHUB_ACTION}/${GITHUB_JOB} on ${GITHUB_REPOSITORY}"
        git push -u "origin" "main"