on:
  workflow_call:
    inputs:
      symver:
        description: The symver value for this check-in
        type: string

      directory:
        description: The directory under the submodule to update
        type: string

      subdirectory:
        description: The directory under the submodule to update
        type: string
        default: /

      update_yaml_file:
        description: The YAML File to be updated
        type: string
        default: ""

      update_yaml_field:
        description: The field in the YAML file to be updated
        type: string
        default: ".image"
      
      update_yaml_value:
        description: The value to update the field in the YAML file
        type: string
        default: ""
      
jobs:
  package:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        path: "${{ inputs.directory }}"

    - name: Checkout
      uses: actions/checkout@v4
      with:
        repository: 'lsc-sde/iac-helm-repository'
        path: './iac/helm/repository'
        token: ${{ secrets.REPOS_RW_TOKEN }}

        

    - name: Install Helm
      run: |
        curl https://baltocdn.com/helm/signing.asc | gpg --dearmor | sudo tee /usr/share/keyrings/helm.gpg > /dev/null
        sudo apt-get install apt-transport-https --yes
        echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/helm.gpg] https://baltocdn.com/helm/stable/debian/ all main" | sudo tee /etc/apt/sources.list.d/helm-stable-debian.list
        sudo apt-get update
        sudo apt-get install helm


    - name: Switch to main branch for repository
      working-directory: "./iac/helm/repository"
      run: |
        git switch main
        git fetch
        git pull

        
    - name: "Switch to main branch for ${{ inputs.directory }}"
      working-directory: "${{ inputs.directory }}"
      run: |
        git switch main
        git fetch
        git pull

    - name: Update YAML File
      working-directory: "${{ inputs.directory }}${{ inputs.subdirectory }}"
      run: |
        if [ -n "${{ inputs.update_yaml_file }}" ]; then
          yq e -i '${{ inputs.update_yaml_field }} = "${{ inputs.update_yaml_value}}"' ${{ inputs.update_yaml_file }}
          cat ${{ inputs.update_yaml_file }}
        fi

    - name: Helm Package
      working-directory: "./iac/helm/repository"
      run: |
        helm package "${GITHUB_WORKSPACE}/${{ inputs.directory }}${{ inputs.subdirectory }}" --version "${{ inputs.symver }}"
        helm repo index ./

    - name: Update Repository
      working-directory: "./iac/helm/repository"
      run: |
        UPDATE_MESSAGE="Updated Package at ${{ inputs.directory }} to version ${{ inputs.symver }}"
        echo "${UPDATE_MESSAGE}"
        git config --global user.name 'lsc-sde'
        git config --global user.email 'shaun.turner1@nhs.net'
        echo "Committing .gitmodules and ${{ inputs.directory }}"

        git add *.tgz
        git add index.yaml
        git commit -m "${UPDATE_MESSAGE}"

        echo "Pushing changes to main branch"
        git push -u "origin" "main"