on:
  workflow_call:
    inputs:
      directory:
        description: The directory under the submodule to update
        type: string

      yamlPath:
        description: The name of the value in the yaml config (if present)
        type: string
        default: ""


jobs:
  semver:
    uses: lsc-sde/lsc-sde/.github/workflows/semver.yaml@main
    with:
      useConfigFile: true

    
  branch:
    uses: lsc-sde/lsc-sde/.github/workflows/flux.yaml@main
    needs:
    - semver
    with:
      symver: ${{ needs.semver.outputs.GitVersion_SemVer }}
      environment: package
      prefix: release
    secrets: inherit
    

  package:
    uses: lsc-sde/lsc-sde/.github/workflows/helm-package.yaml@main
    needs: 
    - semver
    - branch
    with:
      symver: ${{ needs.semver.outputs.GitVersion_SemVer }}
      directory: ${{ inputs.directory }}
    secrets: inherit


  submodule:
    uses: lsc-sde/lsc-sde/.github/workflows/update-submodules.yaml@main
    needs: 
    - semver
    - branch
    - package
    with:
      symver: ${{ needs.semver.outputs.GitVersion_SemVer }}
      directory: ${{ inputs.directory }}
    secrets: inherit

  update-flux:
    if: inputs.yamlPath != ''
    uses: lsc-sde/lsc-sde/.github/workflows/update-yaml.yaml@main
    needs: 
    - semver
    - submodule
    with:
      repository: lsc-sde/iac-flux-lscsde-configuration
      path: "deployment-config.yaml"
      yamlPath: ".data.${{ inputs.yamlPath }}"
      newValue: "${{ needs.semver.outputs.GitVersion_SemVer }}"
    secrets: inherit