on:
  workflow_call:
    outputs:
      GitVersion_Major: 
        description: The major version assigned
        value: ${{ jobs.symver.outputs.GitVersion_Major }}
      GitVersion_Minor: 
        description: The minor version assigned
        value: ${{ jobs.symver.outputs.GitVersion_Minor }}
      GitVersion_Patch: 
        description: The patch version assigned
        value: ${{ jobs.symver.outputs.GitVersion_Patch }}

jobs:
  symver:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    
    - name: Install GitVersion
      uses: gittools/actions/gitversion/setup@v0
      with:
        versionSpec: '5.x'

    - name: Determine Version
      uses: gittools/actions/gitversion/execute@v0
      id: gitversion

    outputs:
      GitVersion_Major: ${{ steps.gitversion.outputs.GitVersion_Major }}
      GitVersion_Minor: ${{ steps.gitversion.outputs.GitVersion_Minor }}
      GitVersion_Patch: ${{ steps.gitversion.outputs.GitVersion_Patch }}