on:
  workflow_call:
    inputs:
      useConfigFile:
        description: Use a config file 
        type: boolean
        default: false

    outputs:
      GitVersion_Major: 
        description: The major version assigned
        value: ${{ jobs.semver.outputs.GitVersion_Major }}
      GitVersion_Minor: 
        description: The minor version assigned
        value: ${{ jobs.semver.outputs.GitVersion_Minor }}
      GitVersion_Patch: 
        description: The patch version assigned
        value: ${{ jobs.semver.outputs.GitVersion_Patch }}
      GitVersion_SemVer: 
        description: The symver assigned
        value: ${{ jobs.semver.outputs.GitVersion_SemVer }}

jobs:
  semver:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    
    - name: Install GitVersion
      uses: gittools/actions/gitversion/setup@v0
      with:
        versionSpec: '5.x'

    - name: Determine Version
      uses: gittools/actions/gitversion/execute@v0
      id: gitversion
      with:
        useConfigFile: ${{ inputs.useConfigFile }}

    outputs:
      GitVersion_Major: ${{ steps.semver.outputs.GitVersion_Major }}
      GitVersion_Minor: ${{ steps.semver.outputs.GitVersion_Minor }}
      GitVersion_Patch: ${{ steps.semver.outputs.GitVersion_Patch }}
      GitVersion_SemVer: ${{ steps.semver.outputs.GitVersion_SemVer }}